# Generated by Django 4.2.9 on 2024-09-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignFeedbackProxy",
            fields=[],
            options={
                "verbose_name": "Feedback Export",
                "verbose_name_plural": "Feedback Exports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cpt.campaign",),
        ),
        migrations.CreateModel(
            name="FormProxy",
            fields=[],
            options={
                "verbose_name": "Feedback Details",
                "verbose_name_plural": "Feedback Details",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cpt.form",),
        ),
    ]
